export default {
    SAVE_MARKETING_PLAN_INFO: 'SAVE_MARKETING_PLAN_INFO',
    GET_MARKETING_PLAN_PAGE_INFO: 'GET_MARKETING_PLAN_PAGE_INFO',
    GET_MARKETING_PLAN_PAGE_INFO: 'GET_MARKETING_PLAN_PAGE_INFO',
    DO_NOTHING: 'DO_NOTHING',
    GET_GAME_MARKETING_LINK: 'GET_GAME_MARKETING_LINK'
}